### ISSUE TITLE
Can you help me? I can't reproducing the preformance on  your MaFengWo dataset with your code.

### ISSUE THREAD

**Issue by ghost** [LianHaiMiao/Attentive-Group-Recommendation#6]

**Comment by LianHaiMiao** [comment]
We are sorry for that the training details are not detailed enough in our paper.
As you can see from the MaFengwo dataset that the number of user-item interaction and group-item interaction are not equal. Thus it's necessary to train user-item interaction more epoch compared to group-item interaction. For example, you can train the user-item 6 times and group-item 1 times.

**Comment by FlashXT** [comment]
I am very appreciate for your reply.I will training the AGREE model as your advise.Thank you！And I have some doubt about the MaFengWo dataset.
In the file "groupRatingNegative.txt"  & "userRatingNegative.txt" I find some blank line between the test negative samples. I use the dataset,py your released read the dataset.I think those blank line may be improve the performance of the model.Can you give the download link of your MaFengWo dataset? Either  GoogleDrive or BaiDuYun is OK. Or can you send your contact ways to my e-mail:SXXT@2015@outlook.com,I hope I can discuss this with you，thank you!

**Comment by LianHaiMiao** [comment]
I'm sorry that the original dataset can not be found... we only have the processed dataset, and I remember there are some tiny differences between the dataset.py of Mafengwo dataset and CAMERA2011 dataset. And if you still have any problem about our paper, please feel free to concat me with my email lianhaimiao@gmail.com . BTW, if you are a Chinese, please email me with Chinese.

**Comment by FlashXT** [comment]
邮件已经发至您的邮箱，期待您的回复，谢谢！
