### ISSUE TITLE
i have receive this issue,can you give me some advice? thanks very much!!

### ISSUE THREAD

**Issue by liheyong** [LianHaiMiao/Attentive-Group-Recommendation#7]
AGREE at embedding size 32, run Iteration:30, NDCG and HR at 5Traceback (most recent call last):  File "E:/Attentive-Group-Recommendation-master/main.py", line 101, in <module>    training(agree, dataset.get_user_dataloader(config.batch_size), epoch, config, 'user')  File "E:/Attentive-Group-Recommendation-master/main.py", line 62, in training    print('Iteration %d, loss is [%.4f ]' % (epoch_id, np.mean(losses)))  File "D:\anaconda\lib\site-packages\numpy\core\fromnumeric.py", line 3118, in mean    out=out, **kwargs)  File "D:\anaconda\lib\site-packages\numpy\core\_methods.py", line 85, in _mean    ret = ret.dtype.type(ret / rcount)AttributeError: 'torch.dtype' object has no attribute 'type'

**Comment by liheyong** [comment]
and, my torch is the new version.

**Comment by LianHaiMiao** [comment]
I guess it may be the wrong numpy version or the torch version, please check their version carefully.

**Comment by liheyong** [comment]
thanks!
